Create temperaturesensor_AHT10.
sinricpro/esp8266-esp32-sdk pull request #200
Opened 2021-07-25 00:23 UTC by jpa-welten

support for a new AHT10 sensor
 * AHT Sensor is connected to I2C on ESP8266 devices --> SCL D1 / SDA D2 
 * To begin, install the necessary library, specifically the Adafruit “AHTX0” package 
 * (you might also get warnings for other libraries missing, likely “Adafruit IO“, and “Adafruit Unified Sensors“: install as needed.)
 * - see https://github.com/adafruit/Adafruit_AHTX0
 * - see https://github.com/adafruit/Adafruit_Sensor
 * - see https://github.com/adafruit/Adafruit_IO_Arduino

2021-07-25 05:38 UTC, sivar2311 requested changes
Hi and thanks again for the new example.
Please see my change requests.
Additionally, please create a separate directory for each example. 
Name the directory exactly the same as the example itself:
`\temperaturesensor\AHT10\AHT10.ino`

2021-07-25 05:38 UTC, sivar2311 commented on examples/temperaturesensor/temperaturesensor_AHT10.
> +#define TEMP_SENSOR_ID    "60faf5acaf7d763d5b0d629e"    // Should look like "5dc1564130xxxxxxxxxxxxxx"
Please remove your credentials
```C++
#define WIFI_SSID         ""
#define WIFI_PASS         ""
#define APP_KEY           ""    // Should look like "de0bxxxx-1x3x-4x3x-ax2x-5dabxxxxxxxx"
#define APP_SECRET        ""    // Should look like "5f36xxxx-x3x7-4x3x-xexe-e86724a9xxxx-4c4axxxx-3x3x-x5xe-x9x3-333d65xxxxxx"
#define TEMP_SENSOR_ID    ""    // Should look like "5dc1564130xxxxxxxxxxxxxx"
```

2021-07-25 05:38 UTC, sivar2311 commented on examples/temperaturesensor/temperaturesensor_AHT10.
> +           float temperature = temp.temperature;
Please fix indention (2 spaces)
```C++
  sensors_event_t hum, temp;
  aht.getEvent(&hum, &temp);
  float humidity = hum.relative_humidity;
  float temperature = temp.temperature; 
```

2021-07-26 16:02 UTC, jpa-welten reviewed
removed my credentials

2021-07-27 03:25 UTC, merged